theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false
color-modes = true
auto-format = true
completion-timeout = 5
completion-replace = true
preview-completion-insert = true
scrolloff = 8
cursorline = true
auto-info = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true

[editor.statusline]
left = ["mode", "file-base-name", "version-control"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true
