[main]
font=JetBrainsMono Nerd Font Mono:size=14

# [colors-dark]
# alpha=1.0
# foreground=f8f4cd
# background=262423
# regular0=1e1e1e # black
# regular1=be0f17 # red
# regular2=868715 # green
# regular3=cc881a # yellow
# regular4=377375 # blue
# regular5=a04b73 # magenta
# regular6=578e57 # cyan
# regular7=ca480e # white
# bright0=262423  # bright black
# bright1=f73028  # bright red
# bright2=aab01e  # bright green
# bright3=f7b125  # bright yellow
# bright4=719586  # bright blue
# bright5=c77089  # bright magenta
# bright6=7db669  # bright cyan
# bright7=fb6a16  # bright white
